### ISSUE TITLE
idpf 0.0.766 fails with kernel 6.12 due to idpf_ethtool.c errors

### ISSUE THREAD

**Issue by JonKohler** [intel/ethernet-linux-idpf#7]
Trying to upgrade our internal production kernel to 6.12 LTS, and hitting the following build failure with the latest available idpf driver cc @etantilov

Anecdotally from the Intel ice driver, this sort of handling was sorted like so:
https://github.com/intel/ethernet-linux-ice/blob/v1.16.3/src/kcompat-generator.sh#L158
https://github.com/intel/ethernet-linux-ice/blob/v1.16.3/src/ice_ethtool.c#L5469

In idpf 0.0.766, similar support was added to kcompat-generator.sh, here:
https://github.com/intel/ethernet-linux-idpf/blob/main/idpf/src/kcompat-generator.sh#L148

But isn't plumbed in these two places:
https://github.com/intel/ethernet-linux-idpf/blob/main/idpf/src/idpf_ethtool.c#L1614
https://github.com/intel/ethernet-linux-idpf/blob/main/idpf/src/idpf_ethtool.c#L1637

```
[idpf] /builddir/build/BUILD/idpf-0.0.766/idpf/src/idpf_ethtool.c: In function 'idpf_get_ts_info':
[idpf] /builddir/build/BUILD/idpf-0.0.766/idpf/src/idpf_ethtool.c:1654:41: error: passing argument 2 of 'ethtool_op_get_ts_info' from incompatible pointer type [-Werror=incompatible-pointer-types]
[idpf]    return ethtool_op_get_ts_info(netdev, info);
[idpf]                                          ^~~~
[idpf] In file included from /builddir/build/BUILD/idpf-0.0.766/idpf/src/kcompat.h:19,
[idpf]                  from /builddir/build/BUILD/idpf-0.0.766/idpf/src/idpf_ethtool.c:4:
[idpf] ./include/linux/ethtool.h:1205:38: note: expected 'struct kernel_ethtool_ts_info *' but argument is of type 'struct ethtool_ts_info *'
[idpf]        struct kernel_ethtool_ts_info *eti);
[idpf]        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
[idpf] /builddir/build/BUILD/idpf-0.0.766/idpf/src/idpf_ethtool.c: At top level:
[idpf] /builddir/build/BUILD/idpf-0.0.766/idpf/src/idpf_ethtool.c:1698:18: error: initialization of 'int (*)(struct net_device *, struct kernel_ethtool_ts_info *)' from incompatible pointer type 'int (*)(struct net_device *, struct ethtool_ts_info *)' [-Werror=incompatible-pointer-types]
[idpf]   .get_ts_info  = idpf_get_ts_info,
[idpf]                   ^~~~~~~~~~~~~~~~
```

**Comment by etantilov** [comment]
Checkout https://github.com/intel/ethernet-linux-idpf/pull/8, which includes a fix for this error.

**Comment by etantilov** [comment]
Jon, could you update this issue once you get a chance to test the 0.0.768 release on 6.12?

**Comment by JonKohler** [comment]
I believe we tried out the manual download of the repo prior to the 768 driver release tarball, we'll try it again shortly. Going to make sure this works with our existing config first, then try out the new one to nail down both

**Comment by JonKohler** [comment]
@etantilov - yep, we did build the latest commit with 6.12, looks good thusfar. Will need to do functional testing, but the compile time issues appear to be good

Also, it compiles with our existing 6.6 internal production kernel, so good on both counts thusfar knock on wood

**Comment by etantilov** [comment]
Fixed in 0.0.768
